### ISSUE TITLE
doubly fatigued

### ISSUE THREAD

**Issue by neliodv** [ChrisScrace/pf2e-fatigue#2]
When there is at least one player online playing, the fatigued condition is being applied 2 times on each player.
When taking a rest, one fatigued condition is removed, but the player continues with another fatigued condition.
Detail: Players are without armor at the time of rest, and all another mods are disabled.

**Comment by ChrisScrace** [comment]
Thanks for reporting this. It should be resolved in the latest version, however the fix requires that the GM (not assistant) is online for the effect to be applied.
